import Head from "next/head";
import Bios from "../components/Bios/Bios";

import Intro from "../components/Intro/intro";
import Services from "../components/Services/Services";
import Technologies from "../components/Technologies/Technologies";

export default function Home() {
  return (
    <div>
      <Head>
        <title>The • Devs</title>
        <meta
          name="Software and Web Development Portfolio For The Dot Devs"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Intro />
        <div className="relative">
          <div className="w-full h-screen absolute bg-circuit-flipped" />
          <div className="p-6 ">
            <Services />
            <Technologies />
            <Bios />
          </div>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
